-- =============================================================================
-- Migration  : V1__create_users_table.sql
-- Description: Create the `users` table for JWT-based authentication
-- Author     : Database Engineer
-- Issue      : #2 (Parent: #1)
-- PostgreSQL : 14+
-- =============================================================================


-- =============================================================================
-- UP MIGRATION
-- =============================================================================

-- Enable pgcrypto for gen_random_uuid() if not already active
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS users (
    -- Primary key: UUID v4, generated server-side by PostgreSQL
    id              UUID            NOT NULL DEFAULT gen_random_uuid(),

    -- Authentication identity — enforced unique at DB level
    email           VARCHAR(255)    NOT NULL,

    -- Stores bcrypt / argon2 hash only; plaintext MUST never be stored
    password_hash   VARCHAR(255)    NOT NULL,

    -- Audit timestamps — always stored in UTC (WITH TIME ZONE)
    created_at      TIMESTAMP WITH TIME ZONE    NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP WITH TIME ZONE    NOT NULL DEFAULT NOW(),

    -- Nullable: NULL means the user has never logged in
    last_login      TIMESTAMP WITH TIME ZONE    NULL,

    -- Soft-disable flag; FALSE blocks login without deleting the record
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,

    -- Constraints
    CONSTRAINT users_pkey          PRIMARY KEY (id),
    CONSTRAINT users_email_unique  UNIQUE      (email)
);

-- -----------------------------------------------------------------------------
-- Indexes
-- -----------------------------------------------------------------------------

-- Supports fast credential lookup during login (WHERE email = $1)
CREATE INDEX IF NOT EXISTS idx_users_email
    ON users (email);

-- Supports filtering active users efficiently (WHERE is_active = TRUE)
CREATE INDEX IF NOT EXISTS idx_users_is_active
    ON users (is_active);

-- -----------------------------------------------------------------------------
-- Comment annotations (visible in pg_description / psql \d+ users)
-- -----------------------------------------------------------------------------

COMMENT ON TABLE  users                 IS 'Registered user accounts for JWT authentication';
COMMENT ON COLUMN users.id              IS 'UUID v4 primary key, generated by gen_random_uuid()';
COMMENT ON COLUMN users.email           IS 'Unique user email address used as login identity';
COMMENT ON COLUMN users.password_hash   IS 'Bcrypt or Argon2 hash of the user password — never plaintext';
COMMENT ON COLUMN users.created_at      IS 'UTC timestamp of account creation';
COMMENT ON COLUMN users.updated_at      IS 'UTC timestamp of last record update';
COMMENT ON COLUMN users.last_login      IS 'UTC timestamp of the most recent successful login; NULL if never logged in';
COMMENT ON COLUMN users.is_active       IS 'FALSE soft-disables the account without deleting it';


-- =============================================================================
-- DOWN MIGRATION
-- =============================================================================
-- WARNING: Executing the DOWN block drops all user data permanently.
--          Run only in development/staging or during a deliberate rollback.
-- =============================================================================

-- DROP INDEX  IF EXISTS idx_users_is_active;
-- DROP INDEX  IF EXISTS idx_users_email;
-- DROP TABLE  IF EXISTS users;
